---
- name: Test SSH connection as user
  hosts: server
  tasks:
    - name: Who Am I 
      command: whoami
    - name: Where Am I
      command: pwd
    - name: Can I sudo
      become: yes
      command: cat /etc/hosts