---
- name: Add or update the existing user on Ubuntu servers

  hosts: server

  become: yes
  roles:
    - user

  vars_prompt:
    - name: "username"
      prompt: "Enter username"
      private: no

    - name: "password"
      prompt: "Enter password"
      encrypt: "md5_crypt"
      salt_size: 7
      confirm: yes

    - name: "id_rsa_path"
      prompt: "Enter id_rsa.pub path"
      default: "~/.ssh/id_rsa.pub"
      private: no

    - name: "sudoers"
      prompt: "Allow user to sudo (y/n)"
      default: 'n'
      private: no

    - name: "passwordless"
      prompt: "Allow user to sudo without a password"
      default: 'n'
      private: no
