---
- name: Add or update user with password
  user:
    name: "{{ username }}" 
    password: "{{ password }}"
    createhome: yes
  when:
    - passwordless == 'n'

- name: Add or update user without a password
  user:
    name: "{{ username }}"
    createhome: yes
  when:
    - passwordless == 'y'

- name: Add or update authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', id_rsa_path) }}"
  when: id_rsa_path is defined

- name: Add user to sudoers, requiring password
  lineinfile:
    dest: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) ALL"
    state: present
    create: yes
  when:
    - sudoers == 'y'
    - passwordless == 'n'

- name: Add user to **passwordless** sudoers
  lineinfile:
    dest: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
  when:
    - sudoers == 'y'
    - passwordless == 'y'

- name: Remove user from sudoers
  file:
    dest: "/etc/sudoers.d/{{ username }}"
    state: absent
  when: sudoers == 'n'
