---
- name: Add or update user and set password
  user:
    name: "{{ username }}" 
    password: "{{ password }}"
    shell: /bin/bash
    createhome: yes

- name: Add or update authorized key
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', id_rsa_path) }}"
  when: id_rsa_path is defined

- name: Add user to sudoers
  lineinfile:
    dest: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) ALL"
    state: present
    create: yes
  when: sudoers == 'y'

- name: Remove user from sudoers
  file:
    dest: "/etc/sudoers.d/{{ username }}"
    state: absent
  when: sudoers == 'n'
